
# -----Video In-----
VIn.path: /mnt/c/Users/and_t/Documents/AROS/Database/kitti_grayscale/dataset/sequences/00/image_0/
#VIn.path: /mnt/d/andreas/AROS/Datasets/kitti_grayscale/dataset/sequences/00/image_0/
#VIn.path: /home/andreas/Documents/Datasets/data_odometry_gray/dataset/sequences/00/image_0/
#VIn.path: /mnt/c/Users/and_t/Documents/AROS/Database/EuRoC/MH_01_easy/mav0/cam0/data/
#VIn.path: /mnt/c/Users/and_t/Documents/AROS/Database/2021-08-17_SEQ1/vehicle0/cam0/A/
VIn.file_format: png
VIn.fps: 24

# -----Camera param(KITTI)-----
Camera.fx: 718.856
Camera.fy: 718.856
Camera.cx: 607.1928
Camera.cy: 185.2157

# -----Camera param(EuRoC)-----
#Camera.fx: 458.654
#Camera.fy: 457.296
#Camera.cx: 367.215
#Camera.cy: 248.375

# -----Camera param(VAROS)-----
#Camera.fx: 985.50724637681159420289855072464
#Camera.fy: 985.50724637681159420289855072464
#Camera.cx: 639.5
#Camera.cy: 359.5

# -----Algorithms-----
Method.motion_prior: none
Method.extractor: orb_os #dd #orb #orb_os
Method.matcher: bf_mono
Method.pose_calculator: G_JET #reproOpt #G_JET #5-point + outlier removal
Method.point_reg_3D: all
Method.point_cull_3D: OoW

# -----Algorithms-----
#Method.motion_prior: gt
#Method.extractor: orb
#Method.matcher: none
#Method.pose_calculator: motion prior
#Method.point_reg_3D: depth_gt
#Method.point_cull_3D: OoW

# -----Video Out-----
VOut.show: true
VOut.record: false
#VOut.rec_path: /mnt/c/Users/and_t/Documents/AROS/Results/Recordings/
#VOut.rec_path: /mnt/d/andreas/AROS/Results/Video/
VOut.rec_path: /home/andreas/Pictures/DJET-VideoOut/

# -----Log out----
Log.save: true
Log.name: poses.txt
Log.path: output/

# -----Incremental Log-----
ILog.save: false
ILog.path: output/IncrementalLog/

# -----UI config-----
UI.timing_show: true
UI.tracking_log_show: true
UI.keypoint_trail_length: 10
UI.GUI_show: true
UI.GUI_size_x: 1024
UI.GUI_size_y: 768
UI.camera_size: 0.15
UI.camera_line_width: 1.0
UI.point_size: 2.0
UI.line_width: 1.0
UI.menu_bar_width: 175


# -----Sequencer parameter config-----
Seq.starting_frame_nr: 0
Seq.frame_buffer_size: 2

# -----Tracker parameter config-----
Trck.tracking_window_length: 50