
# -----Dataset------
Dataset: kitti #kitti #euroc #varos #tartainair

# -----Algorithms-----
Method.preprocessor: none #hf #fft #autocor #blur
Method.motion_prior: none #constant #gt #pre_est
Method.extractor: orb_os #blockFeature #dd #orb #orb_os
Method.matcher: BFMatcher #OF_F #KLT #phaseCorr #BFMatcher
Method.pose_calculator: 5-point #blockShift #motionPrior #reproOpt #G_JET #5-point
Method.point_reg_3D: none #None #all
Method.point_cull_3D: none #None #OoW

# -----Pre-processing-----
Pre-processing:
  Blur:
    kernel_size: 61

# -----Matcher-----
Matcher:
  BFMatcher:
    do_lowes_ratio_test: true
    retain_N_best_matches: -1 # Only retains N best matches. Set as -1 for using all matches.

# -----Parametrisation-----
Methods.param: lie #std, lie

# -----Analysis------
Anlys.main_switch: true
Anlys.kpt_extract: true
Anlys.match: true
Anlys.pose_calculator: true
Anlys.map_reg: true

# -----Incremental Log-----
ILog.save: false
ILog.path: output/IncrementalLog/

# -----UI config-----
UI.display_img: true
UI.GUI_show: true
UI.map_width: 1024
UI.map_height: 768
UI.camera_size: 0.15
UI.camera_line_width: 1.0
UI.point_size: 4.0
UI.line_width: 1.0
UI.menu_bar_width: 175
UI.true_color: true

# -----Sequencer parameter config-----
Seq.auto_start: true
Seq.starting_frame_nr: 0
Seq.frame_skip: 0

# -----Tracker parameter config-----
Trck.short_log.show: true
Trck.log.show: false
Trck.timing_show: false
Trck.tracking_window_length: 50
Trck.init_frame_buffer_size: 1
Trck.out.kpt_trail_length: 1

Trck.out.save: true
Trck.out.name: poses.txt
Trck.out.path: output/
Trck.out.clear_at_init: true

# -----Error handling-----
Err.log: true
Err.log_path: output/err.txt
Err.save_img: false
Err.img_folder: output/img/