
# -----Sequences-----
Data.sequences:
  - abandonedfactory/abandonedfactory/Hard/P000/image_left              #000
  - abandonedfactory/abandonedfactory/Hard/P001/image_left              #001
  - abandonedfactory/abandonedfactory/Hard/P002/image_left              #002
  - abandonedfactory/abandonedfactory/Hard/P003/image_left              #003
  - abandonedfactory/abandonedfactory/Hard/P004/image_left              #004
  - abandonedfactory/abandonedfactory/Hard/P005/image_left              #005
  - abandonedfactory/abandonedfactory/Hard/P006/image_left              #006
  - abandonedfactory/abandonedfactory/Hard/P007/image_left              #007
  - abandonedfactory/abandonedfactory/Hard/P008/image_left              #008
  - abandonedfactory/abandonedfactory/Hard/P009/image_left              #009
  - abandonedfactory/abandonedfactory/Hard/P010/image_left              #010
  - abandonedfactory/abandonedfactory/Hard/P011/image_left              #011
  - abandonedfactory_night/abandonedfactory_night/Hard/P000/image_left  #012
  - abandonedfactory_night/abandonedfactory_night/Hard/P001/image_left  #013
  - abandonedfactory_night/abandonedfactory_night/Hard/P002/image_left  #014
  - abandonedfactory_night/abandonedfactory_night/Hard/P003/image_left  #015
  - abandonedfactory_night/abandonedfactory_night/Hard/P005/image_left  #016
  - abandonedfactory_night/abandonedfactory_night/Hard/P006/image_left  #017
  - abandonedfactory_night/abandonedfactory_night/Hard/P007/image_left  #018
  - abandonedfactory_night/abandonedfactory_night/Hard/P008/image_left  #019
  - abandonedfactory_night/abandonedfactory_night/Hard/P009/image_left  #020
  - abandonedfactory_night/abandonedfactory_night/Hard/P010/image_left  #021
  - abandonedfactory_night/abandonedfactory_night/Hard/P011/image_left  #022
  - abandonedfactory_night/abandonedfactory_night/Hard/P012/image_left  #023
  - abandonedfactory_night/abandonedfactory_night/Hard/P013/image_left  #024
  - abandonedfactory_night/abandonedfactory_night/Hard/P014/image_left  #025
  - amusement/amusement/Hard/P000/image_left                            #026
  - amusement/amusement/Hard/P001/image_left                            #027
  - amusement/amusement/Hard/P002/image_left                            #028
  - amusement/amusement/Hard/P003/image_left                            #029
  - amusement/amusement/Hard/P004/image_left                            #030
  - amusement/amusement/Hard/P005/image_left                            #031
  - amusement/amusement/Hard/P006/image_left                            #032
  - amusement/amusement/Hard/P007/image_left                            #033
  - carwelding/carwelding/Hard/P000/image_left                          #034
  - carwelding/carwelding/Hard/P001/image_left                          #035
  - carwelding/carwelding/Hard/P002/image_left                          #036
  - carwelding/carwelding/Hard/P003/image_left                          #037
  - endofworld/endofworld/Hard/P000/image_left                          #038
  - endofworld/endofworld/Hard/P001/image_left                          #039
  - endofworld/endofworld/Hard/P002/image_left                          #040
  - endofworld/endofworld/Hard/P005/image_left                          #041
  - endofworld/endofworld/Hard/P006/image_left                          #042
  - gascola/gascola/Hard/P000/image_left                                #043
  - gascola/gascola/Hard/P001/image_left                                #044
  - gascola/gascola/Hard/P002/image_left                                #045
  - gascola/gascola/Hard/P003/image_left                                #046
  - gascola/gascola/Hard/P004/image_left                                #047
  - gascola/gascola/Hard/P005/image_left                                #048
  - gascola/gascola/Hard/P006/image_left                                #049
  - gascola/gascola/Hard/P007/image_left                                #050
  - gascola/gascola/Hard/P008/image_left                                #051
  - gascola/gascola/Hard/P009/image_left                                #052
  - hospital/hospital/Hard/P037/image_left                              #053
  - hospital/hospital/Hard/P038/image_left                              #054
  - hospital/hospital/Hard/P039/image_left                              #055
  - hospital/hospital/Hard/P040/image_left                              #056
  - hospital/hospital/Hard/P041/image_left                              #057
  - hospital/hospital/Hard/P042/image_left                              #058
  - hospital/hospital/Hard/P043/image_left                              #059
  - hospital/hospital/Hard/P044/image_left                              #060
  - hospital/hospital/Hard/P045/image_left                              #061
  - hospital/hospital/Hard/P046/image_left                              #062
  - hospital/hospital/Hard/P047/image_left                              #063
  - hospital/hospital/Hard/P048/image_left                              #064
  - hospital/hospital/Hard/P049/image_left                              #065
  - japanesealley/japanesealley/Hard/P000/image_left                    #066
  - japanesealley/japanesealley/Hard/P001/image_left                    #067
  - japanesealley/japanesealley/Hard/P002/image_left                    #068
  - japanesealley/japanesealley/Hard/P003/image_left                    #069
  - japanesealley/japanesealley/Hard/P004/image_left                    #070
  - japanesealley/japanesealley/Hard/P005/image_left                    #071
  - neighborhood/neighborhood/Hard/P000/image_left                      #072
  - neighborhood/neighborhood/Hard/P001/image_left                      #073
  - neighborhood/neighborhood/Hard/P002/image_left                      #074
  - neighborhood/neighborhood/Hard/P003/image_left                      #075
  - neighborhood/neighborhood/Hard/P004/image_left                      #076
  - neighborhood/neighborhood/Hard/P005/image_left                      #077
  - neighborhood/neighborhood/Hard/P006/image_left                      #078
  - neighborhood/neighborhood/Hard/P007/image_left                      #079
  - neighborhood/neighborhood/Hard/P008/image_left                      #080
  - neighborhood/neighborhood/Hard/P009/image_left                      #081
  - neighborhood/neighborhood/Hard/P010/image_left                      #082
  - neighborhood/neighborhood/Hard/P011/image_left                      #083
  - neighborhood/neighborhood/Hard/P012/image_left                      #084
  - neighborhood/neighborhood/Hard/P013/image_left                      #085
  - neighborhood/neighborhood/Hard/P014/image_left                      #086
  - neighborhood/neighborhood/Hard/P015/image_left                      #087
  - neighborhood/neighborhood/Hard/P016/image_left                      #088
  - neighborhood/neighborhood/Hard/P017/image_left                      #089
  - ocean/ocean/Hard/P000/image_left                                    #090
  - ocean/ocean/Hard/P001/image_left                                    #091
  - ocean/ocean/Hard/P002/image_left                                    #092
  - ocean/ocean/Hard/P003/image_left                                    #093
  - ocean/ocean/Hard/P004/image_left                                    #094
  - ocean/ocean/Hard/P005/image_left                                    #095
  - ocean/ocean/Hard/P006/image_left                                    #096
  - ocean/ocean/Hard/P007/image_left                                    #097
  - ocean/ocean/Hard/P008/image_left                                    #098
  - ocean/ocean/Hard/P009/image_left                                    #099
  - office/office/Hard/P000/image_left                                  #100
  - office/office/Hard/P001/image_left                                  #101
  - office/office/Hard/P002/image_left                                  #102
  - office/office/Hard/P003/image_left                                  #103
  - office/office/Hard/P004/image_left                                  #104
  - office/office/Hard/P005/image_left                                  #105
  - office/office/Hard/P006/image_left                                  #106
  - office/office/Hard/P007/image_left                                  #107
  - office2/office2/Hard/P000/image_left                                #108
  - office2/office2/Hard/P001/image_left                                #109
  - office2/office2/Hard/P002/image_left                                #110
  - office2/office2/Hard/P003/image_left                                #111
  - office2/office2/Hard/P004/image_left                                #112
  - office2/office2/Hard/P005/image_left                                #113
  - office2/office2/Hard/P006/image_left                                #114
  - office2/office2/Hard/P007/image_left                                #115
  - office2/office2/Hard/P008/image_left                                #116
  - office2/office2/Hard/P009/image_left                                #117
  - office2/office2/Hard/P010/image_left                                #118
  - seasidetown/seasidetown/Hard/P000/image_left                        #119
  - seasidetown/seasidetown/Hard/P001/image_left                        #120
  - seasidetown/seasidetown/Hard/P002/image_left                        #121
  - seasidetown/seasidetown/Hard/P003/image_left                        #122
  - seasidetown/seasidetown/Hard/P004/image_left                        #123
  - seasonsforest/seasonsforest/Hard/P001/image_left                    #124
  - seasonsforest/seasonsforest/Hard/P002/image_left                    #125
  - seasonsforest/seasonsforest/Hard/P004/image_left                    #126
  - seasonsforest/seasonsforest/Hard/P005/image_left                    #127
  - seasonsforest/seasonsforest/Hard/P006/image_left                    #128
  - soulcity/soulcity/Hard/P000/image_left                              #129
  - soulcity/soulcity/Hard/P001/image_left                              #130
  - soulcity/soulcity/Hard/P002/image_left                              #131
  - soulcity/soulcity/Hard/P003/image_left                              #132
  - soulcity/soulcity/Hard/P004/image_left                              #133
  - soulcity/soulcity/Hard/P005/image_left                              #134
  - soulcity/soulcity/Hard/P008/image_left                              #135
  - soulcity/soulcity/Hard/P009/image_left                              #136
  - westerndesert/westerndesert/Hard/P000/image_left                    #137
  - westerndesert/westerndesert/Hard/P001/image_left                    #138
  - westerndesert/westerndesert/Hard/P002/image_left                    #139
  - westerndesert/westerndesert/Hard/P003/image_left                    #140
  - westerndesert/westerndesert/Hard/P004/image_left                    #141
  - westerndesert/westerndesert/Hard/P005/image_left                    #142
  - westerndesert/westerndesert/Hard/P006/image_left                    #143
  - westerndesert/westerndesert/Hard/P007/image_left                    #144

# -----Source-----
Data.folder: /home/andreas/Documents/Datasets/tartainair/data/          # Workstation

# -----Meta-----
Data.file_format: png
Data.fps: 24

# -----Camera param(KITTI)-----
Camera.fx: 320.0
Camera.fy: 320.0
Camera.cx: 320.0
Camera.cy: 240.0

# -----Sequence Playlist-----
#Data.playlist: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144]
Data.playlist: [0,1,2,3,4,5,6,7,8,9,10,11,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144]